Internal Server Error: /token/
Traceback (most recent call last):
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'CustomTokenObtainPairSerializer' object has no attribute 'is_valid'
"POST /token/ HTTP/1.1" 500 94412
Internal Server Error: /token/
Traceback (most recent call last):
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\varain\AppData\Roaming\Python\Python313\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'CustomTokenObtainPairSerializer' object has no attribute 'is_valid'
"POST /token/ HTTP/1.1" 500 94412
